TRUNCATE  `persona`;
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (1, 'dani', 'Norway', 45,'HOMBRE');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (2, 'juana', 'Borway', 33,'MUJER');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (3, 'xani', 'Hin', 28,'MUJER');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (4, 'gabriel', 'Noray', 75,'HOMBRE');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (5, 'dani', 'Norway', 45,'HOMBRE');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (6, 'juana', 'Borway', 33,'MUJER');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (7, 'jana', 'Jorzt', 28,'MUJER');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (8, 'gabriela', 'ware', 75,'MUJER');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (9, 'ana', 'Herz', 28,'MUJER');
INSERT INTO `persona` (`id`, `nombre`, `apellido`, `edad`, `sexo`) VALUES (10, 'juan', 'Garcia', 34,'HOMBRE');
